// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxK3XeaqJTS54e3jUPpSe8x--UCLuj6Fw',
    appId: '1:733702746815:android:91b22520bc1f766c9b0c0a',
    messagingSenderId: '733702746815',
    projectId: 'authtutorial-3335f',
    storageBucket: 'authtutorial-3335f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgov5QelE8rfBm6aiXBie39WPyJQtt0GU',
    appId: '1:733702746815:ios:45fcdad9aae4b0969b0c0a',
    messagingSenderId: '733702746815',
    projectId: 'authtutorial-3335f',
    storageBucket: 'authtutorial-3335f.firebasestorage.app',
    androidClientId: '733702746815-p5ud4rv8j2e470nu5f9pof2lcrq6p9do.apps.googleusercontent.com',
    iosClientId: '733702746815-e7j6dc1k60obtqnfdgnf2e37ao9c949f.apps.googleusercontent.com',
    iosBundleId: 'com.example.autentication',
  );

}