name: music
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  audioplayers: ^6.6.0
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
  marquee: ^2.3.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/audios/Luan_Santana/
    - assets/audios/Marilia_Mendonca/
    - assets/images/